[build]
  command = "npm run build"     # adjust if your command is different
  publish = "dist"              # adjust to "build" or your actual output folder

[context.main.environment]
  NODE_VERSION = "16.20.2"
